version: '3'

tasks:

  build:
    desc: Build
    cmds:
      - go build -o /dev/null cmd/server/main.go
      - go build -o /dev/null cmd/client/main.go

  proto:
    desc: Generate Go files from protobuf definitions
    cmd: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./proto/*.proto


  server:
    desc: Run server
    cmd: go run cmd/server/main.go

  client:
    desc: Run client
    cmd: go run cmd/client/main.go 5 10
