// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/summation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SummationService_Sum_FullMethodName = "/summation.SummationService/Sum"
)

// SummationServiceClient is the client API for SummationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummationServiceClient interface {
	Sum(ctx context.Context, in *SummationRequest, opts ...grpc.CallOption) (*SummationResponse, error)
}

type summationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSummationServiceClient(cc grpc.ClientConnInterface) SummationServiceClient {
	return &summationServiceClient{cc}
}

func (c *summationServiceClient) Sum(ctx context.Context, in *SummationRequest, opts ...grpc.CallOption) (*SummationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummationResponse)
	err := c.cc.Invoke(ctx, SummationService_Sum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummationServiceServer is the server API for SummationService service.
// All implementations must embed UnimplementedSummationServiceServer
// for forward compatibility.
type SummationServiceServer interface {
	Sum(context.Context, *SummationRequest) (*SummationResponse, error)
	mustEmbedUnimplementedSummationServiceServer()
}

// UnimplementedSummationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummationServiceServer struct{}

func (UnimplementedSummationServiceServer) Sum(context.Context, *SummationRequest) (*SummationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedSummationServiceServer) mustEmbedUnimplementedSummationServiceServer() {}
func (UnimplementedSummationServiceServer) testEmbeddedByValue()                          {}

// UnsafeSummationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummationServiceServer will
// result in compilation errors.
type UnsafeSummationServiceServer interface {
	mustEmbedUnimplementedSummationServiceServer()
}

func RegisterSummationServiceServer(s grpc.ServiceRegistrar, srv SummationServiceServer) {
	// If the following call pancis, it indicates UnimplementedSummationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SummationService_ServiceDesc, srv)
}

func _SummationService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummationServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummationService_Sum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummationServiceServer).Sum(ctx, req.(*SummationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SummationService_ServiceDesc is the grpc.ServiceDesc for SummationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SummationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "summation.SummationService",
	HandlerType: (*SummationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SummationService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/summation.proto",
}
